# Generated by Django 3.2.7 on 2022-01-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='difficulty',
            field=models.CharField(choices=[('E', 'easy'), ('M', 'medium'), ('H', 'hard')], default='M', max_length=2),
        ),
    ]
